site_name: Shopee
site_url: https://joaopc10.github.io/Desafio1-TraineeEngNet-2025-Shopee/

markdown_extensions:
  - tables
  - md_in_html
theme:
  name: material
  palette:
    # Este esquema terá um fundo CLARO (default)
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: blue 

    # Este esquema terá um fundo ESCURO (slate)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      primary: deep orange
icon:
  repo: fontawesome/brands/git-alt

extra_css:
  - assets/css/custom.css
