site_name: Shopee
site_url: https://joaopc10.github.io/Desafio1-TraineeEngNet-2025-Shopee/

nav:
  - Início: index.md
  - Sobre o Projeto: sobre.md
  - Equipe: equipe.md
  - Contato: contato.md
  - elicitacao: elicitacao/introspeccao.md

theme:
  name: material
  language: pt
  font:
    text: Roboto
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Modo escuro
    - scheme: slate
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Modo claro

markdown_extensions:
  - attr_list
  - tables

extra_css:
  - assets/css/custom.css
