site_name: Shopee
site_url: https://joaopc10.github.io/Desafio1-TraineeEngNet-2025-Shopee/

theme:
  name: material
  font:
    text: Roboto
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pt

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Dark mode
      primary: blue
      accent: light blue
      background: "#f5f7fa"
      text: "#22272e"
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Light mode
      primary: blue grey
      accent: cyan
      background: "#22272e"
      text: "#f5f7fa"

markdown_extensions:
  - attr_list
  - tables

extra_css:
  - assets/css/custom.css
